# ビルド用
FROM node:18.12.1-slim

# プロジェクトのルートディレクトリを作業ディレクトリとして設定
WORKDIR /usr/src/app

## パッケージをインストール
COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./
RUN npm ci

# 他のプロジェクトファイルをコピー
COPY . .

EXPOSE 8080

RUN npm run build

CMD ["npm", "run", "preview"]
